#!/bin/sh

DEVICE="HB-Sec-RHS-3"
DEVICE_IMG=hb-sec-rhs-3.png
DEVICE_THUMB=hb-sec-rhs-3_thumb.png
DEVICE_DESC="HB Rotary Handle Sensor with battery state"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
