#!/bin/sh

DEVICE="HB-OU-MOT-SERVO"
DEVICE_IMG=hb-ou-mot-servo.png
DEVICE_THUMB=hb-ou-mot-servo_thumb.png
DEVICE_DESC="Servo motor control"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="RELEASE_AFTER_MOVE"
webuiInsertValue="stringTableHbReleaseAfterMove"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="SERVO_STAY"
webuiInsertValue="stringTableHbServoStay"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="SERVO_MOVE0"
webuiInsertValue="stringTableHbServoMove0"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="SERVO|LEVEL\t\${stringTableHbServoLevel}"
if [ -z "`cat $stringtable_deFile | grep \"SERVO|LEVEL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="SERVO|OLD_LEVEL\t\${stringTableHbServoOldLevel}"
if [ -z "`cat $stringtable_deFile | grep \"SERVO|OLD_LEVEL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="SERVO|RAMP_TIME\t\${stringTableHbServoRampTime}"
if [ -z "`cat $stringtable_deFile | grep \"SERVO|RAMP_TIME"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="RELEASE_AFTER_MOVE\t\${stringTableHbReleaseAfterMove}"
if [ -z "`cat $stringtable_deFile | grep \"RELEASE_AFTER_MOVE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="SERVO_STAY\t\${stringTableHbServoStay}"
if [ -z "`cat $stringtable_deFile | grep \"SERVO_STAY"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="SERVO_MOVE0\t\${stringTableHbServoMove0}"
if [ -z "`cat $stringtable_deFile | grep \"SERVO_MOVE0"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbServoLevel\" : \"Stellwinkel\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbServoLevel\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbServoOldLevel\" : \"Letzter Stellwinkel\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbServoOldLevel\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbServoRampTime\" : \"Anfahrzeit\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbServoRampTime\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbReleaseAfterMove\" : \"Motor nach Positionierung freigeben\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbReleaseAfterMove\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbServoStay\" : \"In aktueller Position verweilen\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbServoStay\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbServoMove0\" : \"Auf 0\&deg; fahren\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbServoMove0\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

### Edit channels.html ###
channelsFile="/www/rega/esp/channels.htm"
channelsInsert="  if (action == \"servoOldVal\")     { Call(\"channels.fn::servoOldVal()\"); }"
if [ -z "`cat $channelsFile | grep \"servoOldVal"`" ]; then
    echo -e $channelsInsert >> $channelsFile
fi