#!/bin/sh

DEVICE="HB-UNI-Sen-DIST-US"
DEVICE_IMG=hb-uni-sen-dist-us.png
DEVICE_THUMB=hb-uni-sen-dist-us_thumb.png
DEVICE_DESC="universeller Ultraschall Entfernungsmesser"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deInsert="HB_GENERIC_DIST|DISTANCE	\${stringTableHbGenericDistDistance} \n"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DIST|DISTANCE"`" ]; then
    sed -i "1s/^/\1$stringtable_deInsert/" $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC_DIST|DISTANCE_OFFSET	\${stringTableHbGenericDistDistanceOffset} \n"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DIST|DISTANCE_OFFSET"`" ]; then
    sed -i "1s/^/\1$stringtable_deInsert/" $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC_DIST|BATTERY_VOLTAGE	\${stringTableHbGenericDistBatteryVoltage} \n"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DIST|BATTERY_VOLTAGE"`" ]; then
    sed -i "1s/^/\1$stringtable_deInsert/" $stringtable_deFile
fi

### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","
translate_deInsert="\n    \"stringTableHbGenericDistDistance\" : \"Abstand\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbGenericDistDistance\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deSearch="\"dummy\" : \"\","
translate_deInsert="\n    \"stringTableHbGenericDistDistanceOffset\" : \"Sensor Offset\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbGenericDistDistanceOffset\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deSearch="\"dummy\" : \"\","
translate_deInsert="\n    \"stringTableHbGenericDistBatteryVoltage\" : \"Batteriespannung\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbGenericDistBatteryVoltage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
