#!/bin/sh

DEVICE="HB-UNI-Sen-DUST"
DEVICE_IMG=hb-uni-sen-dust.png
DEVICE_THUMB=hb-uni-sen-dust_thumb.png
DEVICE_DESC="universeller Feinstaubsensor"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="HB_GENERIC_DUST|HB_PM25\t\${stringTableHbDustPm25}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DUST|HB_PM25"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC_DUST|HB_PM10\t\${stringTableHbDustPm10}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DUST|HB_PM10"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC_DUST|ERROR=ERR_SENSOR_NOT_AVAILABLE\t\${stringTableHBSensorNotAvailable}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DUST|ERROR=ERR_SENSOR_NOT_AVAILABLE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC_DUST|ERROR=ERR_INVALID_CHECKSUM\t\${stringTableHBInvalidChecksum}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DUST|ERROR=ERR_INVALID_CHECKSUM"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC_DUST|ERROR=ERR_INVALID_RESPONSE_ID\t\${stringTableHBInvalidResponse}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DUST|ERROR=ERR_INVALID_RESPONSE_ID"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC_DUST|ERROR=ERR_INVALID_HEAD\t\${stringTableHBInvalidHead}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DUST|ERROR=ERR_INVALID_HEAD"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC_DUST|ERROR=ERR_INVALID_TAIL\t\${stringTableHBInvalidTail}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_DUST|ERROR=ERR_INVALID_TAIL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi


### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbDustPm25\" : \"Partikelgr%F6%DFe PM25\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbDustPm25\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
	
translate_deInsert="\n    \"stringTableHbDustPm10\" : \"Partikelgr%F6%DFe PM10\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbDustPm10\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBSensorNotAvailable\" : \"Sensor nicht verf%FCgbar\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBSensorNotAvailable\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBInvalidChecksum\" : \"Fehler Checksumme\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBInvalidChecksum\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBInvalidResponse\" : \"Fehler Antwort-Daten\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBInvalidResponse\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBInvalidHead\" : \"Fehler ung%FCltiger HEAD\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBInvalidHead\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBInvalidTail\" : \"Fehler ung%FCltiger TAIL\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBInvalidTail\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi