#!/bin/sh

DEVICE="HB-UNI-Sen-TEMP-SC"
DEVICE_IMG=hb-uni-sen-temp-sc.png
DEVICE_THUMB=hb-uni-sen-temp-sc_thumb.png
DEVICE_DESC="Temperatursensor mit Grenzwert-Schliesserkontakt"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="WEATHER|ERROR=HB_ERROR_TEMPSENSOR_FAILURE"
webuiInsertValue="stringTableHBErrorTempSensorFailure"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_PWRSC|STATE=PWRON"
webuiInsertValue="stringTableStatePwrOn"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_PWRSC|STATE=PWROFF"
webuiInsertValue="stringTableStatePwrOff"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CONDSC|STATE=CONDABOVE"
webuiInsertValue="stringTableStateCondAbove"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CONDSC|STATE=CONDBELOW"
webuiInsertValue="stringTableStateCondBelow"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_POWEROFF_BEHAVIUOR"
webuiInsertValue="stringTableHbPowerOffBehaviour"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_POWEROFF_BEHAVIUOR=POB_CONDABOVE"
webuiInsertValue="stringTableHbPobCondAbove"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_POWEROFF_BEHAVIUOR=POB_CONDBELOW"
webuiInsertValue="stringTableHbPobCondBelow"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_POWEROFF_BEHAVIUOR=POB_KEEP"
webuiInsertValue="stringTableHbPobKeep"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deInsert="WEATHER|ERROR=HB_ERROR_TEMPSENSOR_FAILURE\t\${stringTableHBErrorTempSensorFailure}"
if [ -z "`cat $stringtable_deFile | grep \"HB_ERROR_TEMPSENSOR_FAILURE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="HB_PWRSC|STATE=PWRON\t\${stringTableStatePwrOn}"
if [ -z "`cat $stringtable_deFile | grep \"HB_PWRSC|STATE=PWRON"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_PWRSC|STATE=PWROFF\t\${stringTableStatePwrOff}"
if [ -z "`cat $stringtable_deFile | grep \"HB_PWRSC|STATE=PWROFF"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_CONDSC|STATE=CONDABOVE\t\${stringTableStateCondAbove}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CONDSC|STATE=CONDABOVE"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_CONDSC|STATE=CONDBELOW\t\${stringTableStateCondBelow}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CONDSC|STATE=CONDBELOW"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi

stringtable_deInsert="HB_POWEROFF_BEHAVIUOR\t\${stringTableHbPowerOffBehaviour}"
if [ -z "`cat $stringtable_deFile | grep \"HB_POWEROFF_BEHAVIUOR"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_POWEROFF_BEHAVIUOR=POB_CONDABOVE\t\${stringTableHbPobCondAbove}"
if [ -z "`cat $stringtable_deFile | grep \"HB_POWEROFF_BEHAVIUOR=POB_CONDABOVE"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_POWEROFF_BEHAVIUOR=POB_CONDBELOW\t\${stringTableHbPobCondBelow}"
if [ -z "`cat $stringtable_deFile | grep \"HB_POWEROFF_BEHAVIUOR=POB_CONDBELOW"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_POWEROFF_BEHAVIUOR=POB_KEEP\t\${stringTableHbPobKeep}"
if [ -z "`cat $stringtable_deFile | grep \"HB_POWEROFF_BEHAVIUOR=POB_KEEP"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi

### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHBErrorTempSensorFailure\" : \"Fehler Temperatursensor\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBErrorTempSensorFailure\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableStatePwrOn\" : \"Ger%E4t ist EIN\","
if [ -z "`cat $translate_deFile | grep \"stringTableStatePwrOn\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableStatePwrOff\" : \"Ger%E4t ist AUS\","
if [ -z "`cat $translate_deFile | grep \"stringTableStatePwrOff\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableStateCondAbove\" : \"Grenzwert %FCberschritten\","
if [ -z "`cat $translate_deFile | grep \"stringTableStateCondAbove\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableStateCondBelow\" : \"Grenzwert unterschritten\","
if [ -z "`cat $translate_deFile | grep \"stringTableStateCondBelow\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbPobKeep\" : \"unver%E4ndert\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbPobKeep\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbPobCondAbove\" : \"sende Grenzwert %FCberschritten\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbPobCondAbove\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbPobCondBelow\" : \"sende Grenzwert unterschritten\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbPobCondBelow\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbPowerOffBehaviour\" : \"Ausschaltverhalten\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbPowerOffBehaviour\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
