#!/bin/sh

DEVICE="HB-UNI-RGB-LED-CTRL"
DEVICE_IMG=hb-uni-rgb-led-ctrl.png
DEVICE_THUMB=hb-uni-rgb-led-ctrl_thumb.png
DEVICE_DESC="Adressable RGB LED Controller"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
