#!/bin/sh

DEVICE="HB-OU-MOT-SERVO"
DEVICE_IMG=hb-ou-mot-servo.png
DEVICE_THUMB=hb-ou-mot-servo_thumb.png
DEVICE_DESC="Servo motor control"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit channels.html ###
channelsFile="/www/rega/esp/channels.htm"
channelsInsert="\n<%  if (action == \"servoOldVal\")     { Call(\"channels.fn::servoOldVal()\"); } %>"
if [ -z "`cat $channelsFile | grep \"servoOldVal"`" ]; then
    echo -e $channelsInsert >> $channelsFile
fi