#!/bin/sh

DEVICE="HB-LC-Sw2PBU-FM"
DEVICE_IMG=PushButton-2ch-wm.png
DEVICE_THUMB=PushButton-2ch-wm_thumb.png
DEVICE_DESC="HM-LC-Sw2PBU-FM mit alternativer FW"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
