#!/bin/sh

DEVICE="HB-UNI-Sen-RFID-RC"
DEVICE_IMG=hb-uni-sen-rfid-rc.png
DEVICE_THUMB=hb-uni-sen-rfid-rc_thumb.png
DEVICE_DESC="RFID Remote Control"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
