#!/bin/sh

DEVICE="HB-UNI-Sen-WEIGHT"
DEVICE_IMG=hb-uni-sen-weight.png
DEVICE_THUMB=hb-uni-sen-weight_thumb.png
DEVICE_DESC="universeller W\&auml;gesensor"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="HB_GENERIC_WEIGHT|HB_TARA"
webuiInsertValue="stringTableHbGenericWeightTara"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="HB_GENERIC_WEIGHT|HB_WEIGHT\t\${stringTableHbWeight}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_WEIGHT|HB_WEIGHT"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC_WEIGHT|HB_TARA\t\${stringTableHbGenericWeightTara}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC_WEIGHT|HB_TARA"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi


### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbWeight\" : \"Gewicht\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbWeight\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbGenericWeightTara\" : \"Tara\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbGenericWeightTara\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi