#!/bin/sh
# Icon made by Popcic https://www.flaticon.com/authors/popcic from www.flaticon.com 


DEVICE="HB-UNI-Sen-DUMMY-BEACON-V2"
DEVICE_IMG=hb-uni-sen-dummy-beacon.png
DEVICE_THUMB=hb-uni-sen-dummy-beacon_thumb.png
DEVICE_DESC="Dummy Beacon Device V2"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="FD_BROADCAST"
webuiInsertValue="stringTableFdBroadcast"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="RF_TX_POWER"
webuiInsertValue="stringTableRfTxPower"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi


webuiInsertParam="RF_TX_POWER=TX_LOW"
webuiInsertValue="stringTableRfTxPowerLow"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="RF_TX_POWER=TX_MID"
webuiInsertValue="stringTableRfTxPowerMid"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="RF_TX_POWER=TX_HIGH"
webuiInsertValue="stringTableRfTxPowerHigh"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="FD_SIMULATE\t\${stringTableFdSimulate}"
if [ -z "`cat $stringtable_deFile | grep \"FD_SIMULATE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="FD_SEND_EVERY\t\${stringTableFdSendEvery}"
if [ -z "`cat $stringtable_deFile | grep \"FD_SEND_EVERY"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="FD_BROADCAST\t\${stringTableFdBroadcast}"
if [ -z "`cat $stringtable_deFile | grep \"FD_BROADCAST"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="FD_SIMULATE_DEVICETYPE\t\${stringTableFdSimulateDeviceType}"
if [ -z "`cat $stringtable_deFile | grep \"FD_SIMULATE_DEVICETYPE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="FD_SIMULATE_DEVICETYPE_ACTUATOR\t\${stringTableFdSimulateDeviceTypeActuator}"
if [ -z "`cat $stringtable_deFile | grep \"FD_SIMULATE_DEVICETYPE_ACTUATOR"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="FD_SIMULATE_DEVICETYPE_SENSOR\t\${stringTableFdSimulateDeviceTypeSensor}"
if [ -z "`cat $stringtable_deFile | grep \"FD_SIMULATE_DEVICETYPE_SENSOR"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="RF_TX_POWER\t\${stringTableRfTxPower}"
if [ -z "`cat $stringtable_deFile | grep \"RF_TX_POWER"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="RF_TX_POWER=TX_LOW\t\${stringTableRfTxPowerLow}"
if [ -z "`cat $stringtable_deFile | grep \"RF_TX_POWER=TX_LOW"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="RF_TX_POWER=TX_MID\t\${stringTableRfTxPowerMid}"
if [ -z "`cat $stringtable_deFile | grep \"RF_TX_POWER=TX_MID"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="RF_TX_POWER=TX_HIGH\t\${stringTableRfTxPowerHigh}"
if [ -z "`cat $stringtable_deFile | grep \"RF_TX_POWER=TX_HIGH"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi


### Edit translate.lang.stringtable.js ###

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableFdSimulate\" : \"Simuliere Ger%e4t\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdSimulate\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableFdSendEvery\" : \"sende alle\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdSendEvery\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableFdBroadcast\" : \"Broadcast\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdBroadcast\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableFdSimulateDeviceType\" : \"Ger%e4tetyp\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdSimulateDeviceType\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableFdSimulateDeviceTypeActuator\" : \"Aktor\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdSimulateDeviceTypeActuator\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableFdSimulateDeviceTypeSensor\" : \"Sensor\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdSimulateDeviceTypeSensor\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableRfTxPower\" : \"Sendeleistung\","
if [ -z "`cat $translate_deFile | grep \"stringTableRfTxPower\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableRfTxPowerLow\" : \"gering (-30 dBm \/ 12.0 mA)\","
if [ -z "`cat $translate_deFile | grep \"stringTableRfTxPowerLow\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableRfTxPowerMid\" : \"normal (0 dBm \/ 16.8 mA)\","
if [ -z "`cat $translate_deFile | grep \"stringTableRfTxPowerMid\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableRfTxPowerHigh\" : \"hoch (+12 dBm \/ 34.2 mA)\","
if [ -z "`cat $translate_deFile | grep \"stringTableRfTxPowerHigh\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

