#!/bin/sh
# WebUI icon used from http://icons8.com 

DEVICE="HB-LC-Sw12-FM"
DEVICE_IMG=hb-lc-sw12-fm.png
DEVICE_THUMB=hb-lc-sw12-fm_thumb.png
DEVICE_DESC="12fach Schaltaktor"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi