#!/bin/sh

DEVICE="HB-LC-Bl2-RD"
DEVICE_IMG=hb-lc-bl2-rd.png
DEVICE_THUMB=hb-lc-bl2-rd_thumb.png
DEVICE_DESC="HB-LC-Bl2-RD, zwei Rolladenaktoren plus Regensensor"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
