#!/bin/sh

DEVICE="HB-UNI-Sen-IAQ"
DEVICE_DESC="universeller Luftg\&uuml;tesensor"
DEVICE_IMG=hb-uni-sen-iaq.png
DEVICE_THUMB=hb-uni-sen-iaq_thumb.png

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
