#!/bin/sh

DEVICE="HB-RC-12-EP-C"
DEVICE_IMG=hb-rc-12-ep-c.png
DEVICE_THUMB=hb-rc-12-ep-c_thumb.png
DEVICE_DESC="RemoteControl with ePaper Color"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi

###############################################################################
#           Device Description for b/W
###############################################################################
DEVICE="HB-RC-12-EP-BW"
DEVICE_IMG=hb-rc-12-ep-bw.png
DEVICE_THUMB=hb-rc-12-ep-bw_thumb.png
DEVICE_DESC="RemoteControl with ePaper b\/w"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi
