#!/bin/sh

DEVICE="HB-OU-AF-SEN-TEMP"
DEVICE_IMG=hb-ou-af-sen-temp.png
DEVICE_THUMB=hb-ou-af-sen-temp_thumb.png
DEVICE_DESC="AirFlap control with Temperature sensor"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi


### Edit channels.html ###
channelsFile="/www/rega/esp/channels.htm"
channelsInsert="\n<%  if (action == \"airflapOldVal\")     { Call(\"channels.fn::airflapOldVal()\"); } %>"
if [ -z "`cat $channelsFile | grep \"airflapOldVal"`" ]; then
    echo -e $channelsInsert >> $channelsFile
fi