#!/bin/sh

DEVICE="HB-LC-Bl1PBU-FM"
DEVICE_IMG=PushButton-2ch-wm.png
DEVICE_THUMB=PushButton-2ch-wm_thumb.png
DEVICE_DESC="HM-LC-Bl1PBU-FM mit alternativer FW"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

mkdir -p /www/config/easymodes/KEY/localization/de
mkdir -p /www/config/easymodes/KEY/localization/en
mkdir -p /www/config/easymodes/KEY/localization/tr

[[ ! -e /www/config/easymodes/KEY/localization/de/GENERIC.txt ]] && cp /www/config/easymodes/BLIND/localization/de/GENERIC.txt /www/config/easymodes/KEY/localization/de/
[[ ! -e /www/config/easymodes/KEY/localization/de/KEY.txt ]] && cp /www/config/easymodes/BLIND/localization/de/KEY.txt /www/config/easymodes/KEY/localization/de/

[[ ! -e /www/config/easymodes/KEY/localization/en/GENERIC.txt ]] && cp /www/config/easymodes/BLIND/localization/en/GENERIC.txt /www/config/easymodes/KEY/localization/en/
[[ ! -e /www/config/easymodes/KEY/localization/en/KEY.txt ]] && cp /www/config/easymodes/BLIND/localization/en/KEY.txt /www/config/easymodes/KEY/localization/en/

[[ ! -e /www/config/easymodes/KEY/localization/tr/GENERIC.txt ]] && cp /www/config/easymodes/BLIND/localization/tr/GENERIC.txt /www/config/easymodes/KEY/localization/tr/
[[ ! -e /www/config/easymodes/KEY/localization/tr/KEY.txt ]] && cp /www/config/easymodes/BLIND/localization/tr/KEY.txt /www/config/easymodes/KEY/localization/tr/