#!/bin/sh

DEVICE="HB-RC-4-Dis-TH"
DEVICE_IMG=hb-rc-4-dis-th.png
DEVICE_THUMB=hb-rc-4-dis-th_thumb.png
DEVICE_DESC="RemoteControl with Display and Temperature measurement"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="HB_DISPLAY_TIMEOUT"
webuiInsertValue="stringTableHbDisplayTimeout"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_DEFAULT_DISPLAY_MODE"
webuiInsertValue="stringTableHbDefaultDisplayMode"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_DISPLAY_HALF_DEGREE"
webuiInsertValue="stringTableHbDisplayHalfDegree"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_TEMP_AND_HUMIDITY"
webuiInsertValue="stringTableHbTempAndHumidity"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_TEMP_ONLY"
webuiInsertValue="stringTableHbTempOnly"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_EP_SHOW_HEADER"
webuiInsertValue="stringTableHbEpShowHeader"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_HEADERLINE"
webuiInsertValue="stringTableHbHeaderLine"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HBTEXTLINE_UPPER"
webuiInsertValue="stringTableHbTextLineUpper"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi
webuiInsertParam="HBTEXTLINE_LOWER"
webuiInsertValue="stringTableHbTextLineLower"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_HUMIDITY_OFFSET"
webuiInsertValue="stringTableHbHumidityOffset"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_CRGSC|MSG_FOR_POS_A"
webuiInsertValue="stringTableHbCrgscMsgPosA"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CRGSC|MSG_FOR_POS_B"
webuiInsertValue="stringTableHbCrgscMsgPosB"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CRGSC|MSG_FOR_POS_A=CRGOFF"
webuiInsertValue="stringTableMsgPosCrgOff"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CRGSC|MSG_FOR_POS_A=CRGON"
webuiInsertValue="stringTableMsgPosCrgOn"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CRGSC|MSG_FOR_POS_A=NO_MSG"
webuiInsertValue="stringTableRHSMsgPosNoMsg"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CRGSC|MSG_FOR_POS_B=NO_MSG"
webuiInsertValue="stringTableRHSMsgPosNoMsg"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CRGSC|MSG_FOR_POS_B=CRGOFF"
webuiInsertValue="stringTableMsgPosCrgOff"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CRGSC|MSG_FOR_POS_B=CRGON"
webuiInsertValue="stringTableMsgPosCrgOn"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CRGSC|STATE=CRGON"
webuiInsertValue="stringTableStateCrgOn"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CRGSC|STATE=CRGOFF"
webuiInsertValue="stringTableStateCrgOff"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="HB_CRGSC|MSG_FOR_POS_A=CRGOFF\t\${stringTableMsgPosCrgOff}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CRGSC|MSG_FOR_POS_A=CRGOFF"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_CRGSC|MSG_FOR_POS_A=CRGON\t\${stringTableMsgPosCrgOn}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CRGSC|MSG_FOR_POS_A=CRGON"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_CRGSC|MSG_FOR_POS_B=CRGOFF\t\${stringTableMsgPosCrgOff}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CRGSC|MSG_FOR_POS_B=CRGOFF"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_CRGSC|MSG_FOR_POS_B=CRGON\t\${stringTableMsgPosCrgOn}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CRGSC|MSG_FOR_POS_B=CRGON"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_CRGSC|STATE=CRGOFF\t\${stringTableStateCrgOff}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CRGSC|STATE=CRGOFF"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi
stringtable_deInsert="HB_CRGSC|STATE=CRGON\t\${stringTableStateCrgOn}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CRGSC|STATE=CRGON"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi

### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbDisplayTimeout\" : \"Display Timeout\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbDisplayTimeout\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbDefaultDisplayMode\" : \"Standard-Anzeige\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbDefaultDisplayMode\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbDisplayHalfDegree\" : \"Temperatur-Anzeige in 0.5%b0C Schritten\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbDisplayHalfDegree\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbTempAndHumidity\" : \"Temperatur und Luftfeuchte\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbTempAndHumidity\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbTempOnly\" : \"Temperatur\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbTempOnly\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbTextLineUpper\" : \"obere Textzeile\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbTextLineUpper\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbTextLineLower\" : \"untere Textzeile\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbTextLineLower\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbEpShowHeader\" : \"%dcberschrift anzeigen\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbEpShowHeader\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbHeaderLine\" : \"%dcberschrift Text\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbHeaderLine\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbHumidityOffset\" : \"Luftfeuchtigkeit-Offset\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbHumidityOffset\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableMsgPosCrgOn\" : \"Ger%E4t wird aufgeladen\","
if [ -z "`cat $translate_deFile | grep \"stringTableMsgPosCrgOn\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableMsgPosCrgOff\" : \"Ger%E4t wird nicht aufgeladen\","
if [ -z "`cat $translate_deFile | grep \"stringTableMsgPosCrgOff\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbCrgscMsgPosA\" : \"Meldung bei %B5Ger%E4t wird nicht aufgeladen%B5\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbCrgscMsgPosA\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableHbCrgscMsgPosB\" : \"Meldung bei %B5Ger%E4t wird aufgeladen%B5\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbCrgscMsgPosB\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableStateCrgOn\" : \"Ger%E4t wird aufgeladen\","
if [ -z "`cat $translate_deFile | grep \"stringTableStateCrgOn\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi
translate_deInsert="\n    \"stringTableStateCrgOff\" : \"Ger%E4t wird nicht aufgeladen\","
if [ -z "`cat $translate_deFile | grep \"stringTableStateCrgOff\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi

############################################

DEVICE="HB-RC-4-Dis-TH-CRG"
DEVICE_IMG=hb-rc-4-dis-th-crg.png
DEVICE_THUMB=hb-rc-4-dis-th-crg_thumb.png
DEVICE_DESC="RemoteControl with Display and Temperature measurement (LiPo)"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi
