#!/bin/sh

DEVICE="HB-UNI-Sen-PC-WM"
DEVICE_IMG=hb-uni-sen-pc-wm.png
DEVICE_THUMB=hb-uni-sen-pc-wm_thumb.png
DEVICE_DESC="PulseCounter WaterMeter"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="HB_METER_READING"
webuiInsertValue="stringTableHbMeterReading"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_METER_CONSTANT_WATER"
webuiInsertValue="stringTableHbMeterConstantWater"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_ANALOG_LOW_THRESHOLD"
webuiInsertValue="stringTableHbAnalogLowThreshold"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_ANALOG_HIGH_THRESHOLD"
webuiInsertValue="stringTableHbAnalogHighThreshold"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_PULSE_DELAY_MS"
webuiInsertValue="stringTableHbPulseDelayMS"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CHANGE_MODE"
webuiInsertValue="stringTableHbChangeMode"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_COUNT_INITIAL_VALUE"
webuiInsertValue="stringTableHbCountInitialValue"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_GENERIC|ERROR=OAPC_ERROR"
webuiInsertValue="stringTableHbOapcError"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_GENERIC|ERROR=FRAM_ERROR"
webuiInsertValue="stringTableHbFramError"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="HB_METER_READING\t\${stringTableHbMeterReading}"
if [ -z "`cat $stringtable_deFile | grep \"HB_METER_READING"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="HB_METER_CONSTANT_WATER\t\${stringTableHbMeterConstantWater}"
if [ -z "`cat $stringtable_deFile | grep \"HB_METER_CONSTANT_WATER"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="HB_ANALOG_LOW_THRESHOLD\t\${stringTableHbAnalogLowThreshold}"
if [ -z "`cat $stringtable_deFile | grep \"HB_ANALOG_LOW_THRESHOLD"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="HB_ANALOG_HIGH_THRESHOLD\t\${stringTableHbAnalogHighThreshold}"
if [ -z "`cat $stringtable_deFile | grep \"HB_ANALOG_HIGH_THRESHOLD"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="HB_PULSE_DELAY_MS\t\${stringTableHbPulseDelayMS}"
if [ -z "`cat $stringtable_deFile | grep \"HB_PULSE_DELAY_MS"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="HB_CHANGE_MODE\t\${stringTableHbChangeMode}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CHANGE_MODE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="HB_COUNT_INITIAL_VALUE\t\${stringTableHbCountInitialValue}"
if [ -z "`cat $stringtable_deFile | grep \"HB_COUNT_INITIAL_VALUE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="HB_GENERIC|ERROR=OAPC_ERROR\t\${stringTableHbOapcError}"
if [ -z "`cat $stringtable_deFile | grep \"OAPC_ERROR"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="HB_GENERIC|ERROR=FRAM_ERROR\t\${stringTableHbFramError}"
if [ -z "`cat $stringtable_deFile | grep \"FRAM_ERROR"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbMeterReading\" : \"Z%E4hlerstand\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbMeterReading\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbAnalogLowThreshold\" : \"Impulserfassung unterer Analog-Schwellwert\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbAnalogLowThreshold\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbAnalogHighThreshold\" : \"Impulserfassung oberer Analog-Schwellwert\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbAnalogHighThreshold\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbPulseDelayMS\" : \"Impulserfassung Mindestdauer zwischen Impulsen\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbPulseDelayMS\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbCountInitialValue\" : \"initialer Z%E4hlerstand\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbCountInitialValue\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbMeterConstantWater\" : \"Impuls-Z%E4hlerkonstante\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbMeterConstantWater\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbOapcError\" : \"OAPC Fehler\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbOapcError\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbFramError\" : \"FRAM Fehler\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbFramError\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbChangeMode\" : \"Impuls-Erfassungmodus\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbChangeMode\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi