#!/bin/sh
# Icon made by Popcic https://www.flaticon.com/authors/popcic from www.flaticon.com 


DEVICE="HB-UNI-Sen-DUMMY-BEACON"
DEVICE_IMG=hb-uni-sen-dummy-beacon.png
DEVICE_THUMB=hb-uni-sen-dummy-beacon_thumb.png
DEVICE_DESC="Dummy Beacon Device"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="FD_ENABLED"
webuiInsertValue="stringTableFdEnabled"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="FD_ENABLED=TRUE"
webuiInsertValue="stringTableFdEnabledTrue"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi
webuiInsertParam="FD_ENABLED=FALSE"
webuiInsertValue="stringTableFdEnabledFalse"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="FD_DEVICE_ID"
webuiInsertValue="stringTableFdDeviceId"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="FD_CYCLIC_TIMEOUT"
webuiInsertValue="stringTableFdCyclicTimeout"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="FD_STATUS"
webuiInsertValue="stringTableFdStatus"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="FD_ENABLED	\${stringTableFdEnabled} \n"
if [ -z "`cat $stringtable_deFile | grep \"FD_ENABLED"`" ]; then
    sed -i "1s/^/\1$stringtable_deInsert/" $stringtable_deFile
fi
stringtable_deInsert="FD_ENABLED=TRUE	\${stringTableFdEnabledTrue} \n"
if [ -z "`cat $stringtable_deFile | grep \"FD_ENABLED=TRUE"`" ]; then
    sed -i "1s/^/\1$stringtable_deInsert/" $stringtable_deFile
fi
stringtable_deInsert="FD_ENABLED=FALSE	\${stringTableFdEnabledFalse} \n"
if [ -z "`cat $stringtable_deFile | grep \"FD_ENABLED=FALSE"`" ]; then
    sed -i "1s/^/\1$stringtable_deInsert/" $stringtable_deFile
fi
stringtable_deInsert="FD_DEVICE_ID	\${stringTableFdDeviceId} \n"
if [ -z "`cat $stringtable_deFile | grep \"FD_DEVICE_ID"`" ]; then
    sed -i "1s/^/\1$stringtable_deInsert/" $stringtable_deFile
fi
stringtable_deInsert="FD_CYCLIC_TIMEOUT	\${stringTableFdCyclicTimeout} \n"
if [ -z "`cat $stringtable_deFile | grep \"FD_CYCLIC_TIMEOUT"`" ]; then
    sed -i "1s/^/\1$stringtable_deInsert/" $stringtable_deFile
fi
stringtable_deInsert="FD_STATUS	\${stringTableFdStatus} \n"
if [ -z "`cat $stringtable_deFile | grep \"FD_STATUS"`" ]; then
    sed -i "1s/^/\1$stringtable_deInsert/" $stringtable_deFile
fi

### Edit translate.lang.stringtable.js ###

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableFdEnabled\" : \"Telegramm%fcbertragung aktiviert\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdEnabled\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableFdEnabledTrue\" : \"Telegramm%fcbertragung aktiviert\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdEnabledTrue\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableFdEnabledFalse\" : \"Telegramm%fcbertragung deaktiviert\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdEnabledFalse\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableFdDeviceId\" : \"Ger%e4te-ID (dezimal)\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdDeviceId\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableFdCyclicTimeout\" : \"%dcbertragungsintervall\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdCyclicTimeout\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableFdStatus\" : \"Status-Wert\","
if [ -z "`cat $translate_deFile | grep \"stringTableFdStatus\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi