#!/bin/sh

DEVICE="HB-OU-MOT-FAN"
DEVICE_IMG=hb-ou-mot-fan.png
DEVICE_THUMB=hb-ou-mot-fan_thumb.png
DEVICE_DESC="PWM 3-pin fan control"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="ERROR=FAN_RPM_FAIL"
webuiInsertValue="stringTableHBFanRpmFailure"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_GENERIC|HB_RPM_ERRMIN"
webuiInsertValue="stringTableHBRpmErrorMin"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="FAN|LEVEL\t\${stringTableHbFanLevel}"
if [ -z "`cat $stringtable_deFile | grep \"FAN|LEVEL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="FAN|OLD_LEVEL\t\${stringTableHbFanOldLevel}"
if [ -z "`cat $stringtable_deFile | grep \"FAN|OLD_LEVEL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="FAN|RAMP_TIME\t\${stringTableHbFanRampTime}"
if [ -z "`cat $stringtable_deFile | grep \"FAN|RAMP_TIME"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC|HB_RPM\t\${stringTableHbGenericRpm}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC|HB_RPM"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="ERROR=FAN_RPM_FAIL\t\${stringTableHBFanRpmFailure}"
if [ -z "`cat $stringtable_deFile | grep \"ERROR=FAN_RPM_FAIL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_GENERIC|HB_RPM_ERRMIN\t\${stringTableHBRpmErrorMin}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC|HB_RPM_ERRMIN"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbFanLevel\" : \"L%fcfterleistung\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbFanLevel\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbFanOldLevel\" : \"Letzte L%fcfterleistung\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbFanOldLevel\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbFanRampTime\" : \"Anfahrzeit\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbFanRampTime\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbGenericRpm\" : \"Drehzahl\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbGenericRpm\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBFanRpmFailure\" : \"Fehler Drehzahl%fcberwachung\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBFanRpmFailure\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBRpmErrorMin\" : \"Drehzahl%FCberwachung%20Mindestumdrehungen%20%280%3Ddeaktiviert%29\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBRpmErrorMin\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

### Edit channels.html ###
channelsFile="/www/rega/esp/channels.htm"
channelsInsert="\n<%  if (action == \"fanOldVal\")     { Call(\"channels.fn::fanOldVal()\"); } %>"
if [ -z "`cat $channelsFile | grep \"fanOldVal"`" ]; then
    echo -e $channelsInsert >> $channelsFile
fi

######################################################

DEVICE="HB-OU-MOT-FAN-RPM"
DEVICE_IMG=hb-ou-mot-fan.png
DEVICE_THUMB=hb-ou-mot-fan_thumb.png
DEVICE_DESC="PWM 4-pin fan control"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

