#!/bin/sh
# WebUI icon used from http://icons8.com 

DEVICE="HB-UNI-SenAct-4-4-SC"
DEVICE_IMG=hb-uni-senact-4-4.png
DEVICE_THUMB=hb-uni-senact-4-4_thumb.png
DEVICE_DESC="4x Aktor u. 4x Kontakt"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

############################################################################################################################

DEVICE="HB-UNI-SenAct-4-4-RC"
DEVICE_IMG=hb-uni-senact-4-4.png
DEVICE_THUMB=hb-uni-senact-4-4_thumb.png
DEVICE_DESC="4x Aktor u. 4x Taster"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi


############################################################################################################################

DEVICE="HB-UNI-SenAct-4-4-SC-BAT"
DEVICE_IMG=hb-uni-senact-4-4-bat.png
DEVICE_THUMB=hb-uni-senact-4-4-bat_thumb.png
DEVICE_DESC="4x Aktor u. 4x Kontakt (Batteriebetrieb)"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

############################################################################################################################

DEVICE="HB-UNI-SenAct-4-4-RC-BAT"
DEVICE_IMG=hb-uni-senact-4-4-bat.png
DEVICE_THUMB=hb-uni-senact-4-4-bat_thumb.png
DEVICE_DESC="4x Aktor u. 4x Taster (Batteriebetrieb)"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

############################################################################################################################
