#!/bin/sh

DEVICE="HB-CDL-6"
DEVICE_IMG=hb-cdl-6.png
DEVICE_THUMB=hb-cdl-6_thumb.png
DEVICE_DESC="Codelock device"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi


webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"


webuiInsertParam="HB_ACTIVE_HSV_COLOR"
webuiInsertValue="stringTableHbActiveHsvColor"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_PRGOGRAM_HSV_COLOR"
webuiInsertValue="stringTableHbProgramHsvColor"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_TOUCHED_BRIGHTNESS"
webuiInsertValue="stringTableHbTouchedBrightness"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_DIMMED_BRIGHTNESS"
webuiInsertValue="stringTableHbDimmedBrightness"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi

webuiInsertParam="HB_RINGER_CHANNEL"
webuiInsertValue="stringTableHbRingerChannel"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile; fi



stringtable_deFile="/www/config/stringtable_de.txt"


stringtable_deInsert="HB_ACTIVE_HSV_COLOR\t\${stringTableHbActiveHsvColor}"
if [ -z "`cat $stringtable_deFile | grep \"HB_ACTIVE_HSV_COLOR"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi

stringtable_deInsert="HB_PRGOGRAM_HSV_COLOR\t\${stringTableHbProgramHsvColor}"
if [ -z "`cat $stringtable_deFile | grep \"HB_PRGOGRAM_HSV_COLOR"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi

stringtable_deInsert="HB_TOUCHED_BRIGHTNESS\t\${stringTableHbTouchedBrightness}"
if [ -z "`cat $stringtable_deFile | grep \"HB_TOUCHED_BRIGHTNESS"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi

stringtable_deInsert="HB_DIMMED_BRIGHTNESS\t\${stringTableHbDimmedBrightness}"
if [ -z "`cat $stringtable_deFile | grep \"HB_DIMMED_BRIGHTNESS"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi

stringtable_deInsert="HB_RINGER_CHANNEL\t\${stringTableHbRingerChannel}"
if [ -z "`cat $stringtable_deFile | grep \"HB_RINGER_CHANNEL"`" ]; then echo -e $stringtable_deInsert >> $stringtable_deFile; fi



### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbActiveHsvColor\" : \"Beleuchtung Betrieb\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbActiveHsvColor\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi

translate_deInsert="\n    \"stringTableHbProgramHsvColor\" : \"Beleuchtung Setup\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbProgramHsvColor\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi

translate_deInsert="\n    \"stringTableHbTouchedBrightness\" : \"Helligkeit aktiv  \","
if [ -z "`cat $translate_deFile | grep \"stringTableHbTouchedBrightness\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi

translate_deInsert="\n    \"stringTableHbDimmedBrightness\" : \"Helligkeit gedimmt\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbDimmedBrightness\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi

translate_deInsert="\n    \"stringTableHbRingerChannel\" : \"Klingel %FCber Kanal\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbRingerChannel\"`" ]; then sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile; fi



### Patch some files ###

