#!/bin/sh
# WebUI icon used from http://icons8.com 

DEVICE="HB-UNI-SenAct-8-8-SC"
DEVICE_IMG=hb-uni-senact-8-8.png
DEVICE_THUMB=hb-uni-senact-8-8_thumb.png
DEVICE_DESC="8x Aktor u. 8x Kontakt"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

############################################################################################################################

DEVICE="HB-UNI-SenAct-8-8-RC"
DEVICE_IMG=hb-uni-senact-8-8.png
DEVICE_THUMB=hb-uni-senact-8-8_thumb.png
DEVICE_DESC="8x Aktor u. 8x Taster"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

############################################################################################################################

DEVICE="HB-UNI-SenAct-8-8-SC-BAT"
DEVICE_IMG=hb-uni-senact-8-8-bat.png
DEVICE_THUMB=hb-uni-senact-8-8-bat_thumb.png
DEVICE_DESC="8x Aktor u. 8x Kontakt (Batteriebetrieb)"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

############################################################################################################################

DEVICE="HB-UNI-SenAct-8-8-RC-BAT"
DEVICE_IMG=hb-uni-senact-8-8-bat.png
DEVICE_THUMB=hb-uni-senact-8-8-bat_thumb.png
DEVICE_DESC="8x Aktor u. 8x Taster (Batteriebetrieb)"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

############################################################################################################################
