#!/bin/sh

DEVICE="HB-OU-MOT-FAN"
DEVICE_IMG=hb-ou-mot-fan.png
DEVICE_THUMB=hb-ou-mot-fan_thumb.png
DEVICE_DESC="PWM fan control"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit channels.html ###
channelsFile="/www/rega/esp/channels.htm"
channelsInsert="\n<%  if (action == \"fanOldVal\")     { Call(\"channels.fn::fanOldVal()\"); } %>"
if [ -z "`cat $channelsFile | grep \"fanOldVal"`" ]; then
    echo -e $channelsInsert >> $channelsFile
fi

######################################################

DEVICE="HB-OU-MOT-FAN-RPM"
DEVICE_IMG=hb-ou-mot-fan.png
DEVICE_THUMB=hb-ou-mot-fan_thumb.png
DEVICE_DESC="PWM fan control with rpm monitoring"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
