#!/bin/sh

DEVICE="HB-UNI-Sen-LEV-US"
DEVICE_IMG=hb-uni-sen-lev-us.png
DEVICE_THUMB=hb-uni-sen-lev-us_thumb.png
DEVICE_DESC="universeller Ultraschall F\&uuml;llstandsmesser"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="CAPACITIVE_FILLING_LEVEL_SENSOR|DISTANCE_OFFSET"
webuiInsertValue="stringTableCapacitiveFillingSensorDistanceOffset"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi
webuiInsertParam="CAPACITIVE_FILLING_LEVEL_SENSOR|SENSOR_TYPE"
webuiInsertValue="stringTableCapacitiveFillingSensorSensorType"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="CAPACITIVE_FILLING_LEVEL_SENSOR|BATTERY_VOLTAGE\t\${stringTableCapacitiveFillingSensorBatteryVoltage}"
if [ -z "`cat $stringtable_deFile | grep \"CAPACITIVE_FILLING_LEVEL_SENSOR|BATTERY_VOLTAGE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="CAPACITIVE_FILLING_LEVEL_SENSOR|FILLING_LITER\t\${stringTableCapacitiveFillingSensorFillingLiter}"
if [ -z "`cat $stringtable_deFile | grep \"CAPACITIVE_FILLING_LEVEL_SENSOR|FILLING_LITER"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="CAPACITIVE_FILLING_LEVEL_SENSOR|FILLING_HEIGHT\t\${stringTableCapacitiveFillingSensorFillingHeight}"
if [ -z "`cat $stringtable_deFile | grep \"CAPACITIVE_FILLING_LEVEL_SENSOR|FILLING_HEIGHT"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="CAPACITIVE_FILLING_LEVEL_SENSOR|SENSOR_TYPE\t\${stringTableCapacitiveFillingSensorSensorType}"
if [ -z "`cat $stringtable_deFile | grep \"CAPACITIVE_FILLING_LEVEL_SENSOR|SENSOR_TYPE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="CAPACITIVE_FILLING_LEVEL_SENSOR|DISTANCE_OFFSET\t\${stringTableCapacitiveFillingSensorDistanceOffset}"
if [ -z "`cat $stringtable_deFile | grep \"CAPACITIVE_FILLING_LEVEL_SENSOR|DISTANCE_OFFSET"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableCapacitiveFillingSensorBatteryVoltage\" : \"Batteriespannung\","
if [ -z "`cat $translate_deFile | grep \"stringTableCapacitiveFillingSensorBatteryVoltage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableCapacitiveFillingSensorFillingLiter\" : \"Liter\","
if [ -z "`cat $translate_deFile | grep \"stringTableCapacitiveFillingSensorFillingLiter\"`" ]; then
        sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableCapacitiveFillingSensorFillingHeight\" : \"Aktuelle F%FCllh%F6he\","
if [ -z "`cat $translate_deFile | grep \"stringTableCapacitiveFillingSensorFillingHeight\"`" ]; then
        sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableCapacitiveFillingSensorSensorType\" : \"Sensortyp\","
if [ -z "`cat $translate_deFile | grep \"stringTableCapacitiveFillingSensorSensorType\"`" ]; then
        sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableCapacitiveFillingSensorDistanceOffset\" : \"Ultraschallsensor Abstand Offset\","
if [ -z "`cat $translate_deFile | grep \"stringTableCapacitiveFillingSensorDistanceOffset\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
