#!/bin/sh
# Icon made by Popcic https://www.flaticon.com/authors/popcic from www.flaticon.com 


DEVICE="HB-UNI-Sen-DUMMY-BEACON-V2"
DEVICE_IMG=hb-uni-sen-dummy-beacon.png
DEVICE_THUMB=hb-uni-sen-dummy-beacon_thumb.png
DEVICE_DESC="Dummy Beacon Device V2"

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

case "$1" in
    ""|install)
     devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"
     if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi
    ;;

    uninstall)
     sed -i "s/\($devdescrInsert\)//g" $devdescrFile

     rm -f /www/config/img/devices/250/$DEVICE_IMG
     rm -f /www/config/img/devices/50/$DEVICE_THUMB
    ;;     
esac