#!/bin/sh

DEVICE="HB-DIS-EP-42BW"
DEVICE_IMG=hb-dis-ep-42bw.png
DEVICE_THUMB=hb-dis-ep-42bw_thumb.png
DEVICE_DESC="battery powered ePaper Display 4.2 b\/w"

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

case "$1" in
    ""|install)
     devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"
     if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi
    ;;

    uninstall)
     sed -i "s/\($devdescrInsert\)//g" $devdescrFile

     rm -f /www/config/img/devices/250/$DEVICE_IMG
     rm -f /www/config/img/devices/50/$DEVICE_THUMB
    ;;     
esac

######################################################################

DEVICE="HB-DIS-EP-42BW-MAINS"
DEVICE_IMG=hb-dis-ep-42bw-mains.png
DEVICE_THUMB=hb-dis-ep-42bw-mains_thumb.png
DEVICE_DESC="mains powered ePaper Display 4.2 b\/w"

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

case "$1" in
    ""|install)
     devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"
     if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi
    ;;

    uninstall)
     sed -i "s/\($devdescrInsert\)//g" $devdescrFile

     rm -f /www/config/img/devices/250/$DEVICE_IMG
     rm -f /www/config/img/devices/50/$DEVICE_THUMB
    ;;     
esac

######################################################################

DEVICE="HB-DIS-EP-75BW"
DEVICE_IMG=hb-dis-ep-75bw.png
DEVICE_THUMB=hb-dis-ep-75bw_thumb.png
DEVICE_DESC="battery powered ePaper Display 7.5 b\/w"

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

case "$1" in
    ""|install)
     devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"
     if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi
    ;;

    uninstall)
     sed -i "s/\($devdescrInsert\)//g" $devdescrFile

     rm -f /www/config/img/devices/250/$DEVICE_IMG
     rm -f /www/config/img/devices/50/$DEVICE_THUMB
    ;;     
esac

######################################################################

DEVICE="HB-DIS-EP-75BW-MAINS"
DEVICE_IMG=hb-dis-ep-75bw-mains.png
DEVICE_THUMB=hb-dis-ep-75bw-mains_thumb.png
DEVICE_DESC="mains powered ePaper Display 7.5 b\/w"

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

case "$1" in
    ""|install)
     devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"
     if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi
    ;;

    uninstall)
     sed -i "s/\($devdescrInsert\)//g" $devdescrFile

     rm -f /www/config/img/devices/250/$DEVICE_IMG
     rm -f /www/config/img/devices/50/$DEVICE_THUMB
    ;;     
esac

######################################################################
