#!/bin/sh

DEVICE="HB-UNI-Sen-LDR-SC"
DEVICE_IMG=hb-uni-sen-ldr-sc.png
DEVICE_THUMB=hb-uni-sen-ldr-sc_thumb.png
DEVICE_DESC="LDR-Ger\&auml;tesensor mit Schliesserkontakt"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="HB_LDRSC|MSG_FOR_POS_A"
webuiInsertValue="stringTableHbLdrscMsgPosA"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|MSG_FOR_POS_B"
webuiInsertValue="stringTableHbLdrscMsgPosB"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|MSG_FOR_POS_A=LDROFF"
webuiInsertValue="stringTableMsgPosLdrOff"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|MSG_FOR_POS_A=LDRON"
webuiInsertValue="stringTableMsgPosLdrOn"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|MSG_FOR_POS_A=NO_MSG"
webuiInsertValue="stringTableRHSMsgPosNoMsg"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|MSG_FOR_POS_B=NO_MSG"
webuiInsertValue="stringTableRHSMsgPosNoMsg"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|MSG_FOR_POS_B=LDROFF"
webuiInsertValue="stringTableMsgPosLdrOff"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|MSG_FOR_POS_B=LDRON"
webuiInsertValue="stringTableMsgPosLdrOn"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|STATE=LDRON"
webuiInsertValue="stringTableStateLdrOn"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|STATE=LDROFF"
webuiInsertValue="stringTableStateLdrOff"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_LDRSC|LDR_THRESHOLD"
webuiInsertValue="stringTableHbLdrscThreshold"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="HB_LDRSC|MSG_FOR_POS_A=LDROFF\t\${stringTableMsgPosLdrOff}"
if [ -z "`cat $stringtable_deFile | grep \"HB_LDRSC|MSG_FOR_POS_A=LDROFF"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_LDRSC|MSG_FOR_POS_A=LDRON\t\${stringTableMsgPosLdrOn}"
if [ -z "`cat $stringtable_deFile | grep \"HB_LDRSC|MSG_FOR_POS_A=LDRON"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_LDRSC|MSG_FOR_POS_B=LDROFF\t\${stringTableMsgPosLdrOff}"
if [ -z "`cat $stringtable_deFile | grep \"HB_LDRSC|MSG_FOR_POS_B=LDROFF"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_LDRSC|MSG_FOR_POS_B=LDRON\t\${stringTableMsgPosLdrOn}"
if [ -z "`cat $stringtable_deFile | grep \"HB_LDRSC|MSG_FOR_POS_B=LDRON"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_LDRSC|LDR_THRESHOLD\t\${stringHbLdrscThreshold}"
if [ -z "`cat $stringtable_deFile | grep \"HB_LDRSC|LDR_THRESHOLD"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_LDRSC|STATE=LDROFF\t\${stringTableStateLdrOff}"
if [ -z "`cat $stringtable_deFile | grep \"HB_LDRSC|STATE=LDROFF"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_LDRSC|STATE=LDRON\t\${stringTableStateLdrOn}"
if [ -z "`cat $stringtable_deFile | grep \"HB_LDRSC|STATE=LDRON"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi


### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableMsgPosLdrOn\" : \"Licht erkannt\","
if [ -z "`cat $translate_deFile | grep \"stringTableMsgPosLdrOn\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableMsgPosLdrOff\" : \"Kein Licht erkannt\","
if [ -z "`cat $translate_deFile | grep \"stringTableMsgPosLdrOff\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbLdrscMsgPosA\" : \"Meldung bei Unterschreiten der LDR Schwelle\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbLdrscMsgPosA\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbLdrscMsgPosB\" : \"Meldung bei %DCberschreiten der LDR Schwelle\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbLdrscMsgPosB\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbLdrscThreshold\" : \"LDR Schwelle\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbLdrscThreshold\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableStateLdrOn\" : \"LDR Zustand: Licht erkannt\","
if [ -z "`cat $translate_deFile | grep \"stringTableStateLdrOn\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableStateLdrOff\" : \"LDR Zustand: Kein Licht erkannt\","
if [ -z "`cat $translate_deFile | grep \"stringTableStateLdrOff\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
