#!/bin/sh

DEVICE="HB-OU-RGB-TEALIGHT"
DEVICE_IMG=hb-ou-rgb-tealight.png
DEVICE_THUMB=hb-ou-rgb-tealight_thumb.png
DEVICE_DESC="mains powered tealight with WS2812B RGB LED"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

##########################################################################################################################

DEVICE="HB-OU-RGB-TEALIGHT-BAT"
DEVICE_IMG=hb-ou-rgb-tealight-bat.png
DEVICE_THUMB=hb-ou-rgb-tealight-bat_thumb.png
DEVICE_DESC="battery powered tealight with WS2812B RGB LED"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
