#!/bin/sh

DEVICE="HB-RC-2-PBU-LED"
DEVICE_IMG=hb-rc-2-pbu-led.png
DEVICE_THUMB=hb-rc-2-pbu-led_thumb.png
DEVICE_DESC="2 remote channel push button with led"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
