#!/bin/sh

DEVICE="HB-LC-Bl1-FM-BAT"
DEVICE_IMG=7_hm-lc-bl1-fm.png
DEVICE_THUMB=7_hm-lc-bl1-fm_thumb.png
DEVICE_DESC="battery powered radio-controlled blind actuator 1-channel (flush-mount)"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

#######################################

DEVICE="HB-LC-Bl1-Velux"
DEVICE_IMG=7_hm-lc-bl1-fm.png
DEVICE_THUMB=7_hm-lc-bl1-fm_thumb.png
DEVICE_DESC="battery powered radio-controlled blind actuator 1-channel for Velux"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
