#!/bin/sh
# Icon from https://www.flaticon.com/free-icon/ammeter_70868
DEVICE="HB-UNI-Sen-CURRENT"
DEVICE_IMG=hb-uni-sen-current.png
DEVICE_THUMB=hb-uni-sen-current_thumb.png
DEVICE_DESC="universeller Stromsensor"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="HB_GENERIC|CURRENT"
webuiInsertValue="stringTablePowerMeterCurrent"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_SAMPLE_TIME"
webuiInsertValue="stringTableHBSampleTime"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_MEASURE_INTERVAL"
webuiInsertValue="stringTableHBMeasureInterval"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CONDITIONCHECK_AVERAGE"
webuiInsertValue="stringTableHBConditionCheckAverage"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CHECK_EACH_MEASURE"
webuiInsertValue="stringTableHBCheckEachMeasure"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HB_CHECK_AVERAGE"
webuiInsertValue="stringTableHBCheckAverage"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="ERROR=CURRENTSENSOR_FAIL"
webuiInsertValue="stringTableHBCurrentSensorFailure"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi


### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="HB_GENERIC|CURRENT\t\${stringTablePowerMeterCurrent}"
if [ -z "`cat $stringtable_deFile | grep \"HB_GENERIC|CURRENT"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_SAMPLE_TIME\t\${stringTableHBSampleTime}"
if [ -z "`cat $stringtable_deFile | grep \"HB_SAMPLE_TIME"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_MEASURE_INTERVAL\t\${stringTableHBMeasureInterval}"
if [ -z "`cat $stringtable_deFile | grep \"HB_MEASURE_INTERVAL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_CONDITIONCHECK_AVERAGE\t\${stringTableHBConditionCheckAverage}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CONDITIONCHECK_AVERAGE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_CHECK_EACH_MEASURE\t\${stringTableHBCheckEachMeasure}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CHECK_EACH_MEASURE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HB_CHECK_AVERAGE\t\${stringTableHBCheckAverage}"
if [ -z "`cat $stringtable_deFile | grep \"HB_CHECK_AVERAGE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="ERROR=CURRENTSENSOR_FAIL\t\${stringTableHBCurrentSensorFailure}"
if [ -z "`cat $stringtable_deFile | grep \"ERROR=CURRENTSENSOR_FAIL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHBSampleTime\" : \"Messdauer (Sampletime)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBSampleTime\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBMeasureInterval\" : \"Messintervall\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBMeasureInterval\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBConditionCheckAverage\" : \"Pr%fcfung auf Grenzwerte\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBConditionCheckAverage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableHBCheckEachMeasure\" : \"bei jeder Messung\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBCheckEachMeasure\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBCheckAverage\" : \"Mittelwert\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBCheckAverage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBCurrentSensorFailure\" : \"Fehler Stromsensor\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBCurrentSensorFailure\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

