#!/bin/sh

DEVICE="HB-OU-MOT-FAN"
DEVICE_IMG=hb-ou-mot-fan.png
DEVICE_THUMB=hb-ou-mot-fan_thumb.png
DEVICE_DESC="PWM fan control"

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

case "$1" in
    ""|install)
     devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"
     if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi

     ### Edit channels.html ###
     channelsFile="/www/rega/esp/channels.htm"
     channelsInsert="\n<%  if (action == \"fanOldVal\")     { Call(\"channels.fn::fanOldVal()\"); } %>"
     if [ -z "`cat $channelsFile | grep \"fanOldVal"`" ]; then
         echo -e $channelsInsert >> $channelsFile
     fi

    ;;

    uninstall)
     sed -i "s/\($devdescrInsert\)//g" $devdescrFile

     channelsFile="/www/rega/esp/channels.htm"
     channelsSearch="fanOldVal"
     sed -i "/\(${channelsSearch}\)/d" $channelsFile

     rm -f /www/config/img/devices/250/$DEVICE_IMG
     rm -f /www/config/img/devices/50/$DEVICE_THUMB
    ;;     
esac



######################################################

DEVICE="HB-OU-MOT-FAN-RPM"
DEVICE_IMG=hb-ou-mot-fan.png
DEVICE_THUMB=hb-ou-mot-fan_thumb.png
DEVICE_DESC="PWM fan control with rpm monitoring"

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

case "$1" in
    ""|install)
     devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"
     if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi
    ;;

    uninstall)
     sed -i "s/\($devdescrInsert\)//g" $devdescrFile

     rm -f /www/config/img/devices/250/$DEVICE_IMG
     rm -f /www/config/img/devices/50/$DEVICE_THUMB
    ;;     
esac
