#!/bin/sh

DEVICE="HB-RC-4-Dis-TH"
DEVICE_IMG=hb-rc-4-dis-th.png
DEVICE_THUMB=hb-rc-4-dis-th_thumb.png
DEVICE_DESC="RemoteControl with Display and Temperature measurement"

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

case "$1" in
    ""|install)
     devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"
     if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi
    ;;

    uninstall)
     sed -i "s/\($devdescrInsert\)//g" $devdescrFile

     rm -f /www/config/img/devices/250/$DEVICE_IMG
     rm -f /www/config/img/devices/50/$DEVICE_THUMB
    ;;     
esac

############################################

DEVICE="HB-RC-4-Dis-TH-CRG"
DEVICE_IMG=hb-rc-4-dis-th-crg.png
DEVICE_THUMB=hb-rc-4-dis-th-crg_thumb.png
DEVICE_DESC="RemoteControl with Display and Temperature measurement (LiPo)"

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

case "$1" in
    ""|install)
     devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"
     if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile; fi
    ;;

    uninstall)
     sed -i "s/\($devdescrInsert\)//g" $devdescrFile

     rm -f /www/config/img/devices/250/$DEVICE_IMG
     rm -f /www/config/img/devices/50/$DEVICE_THUMB
    ;;     
esac