#!/bin/sh

DEVICE="HB-UNI-Sen-IAQ"
DEVICE_DESC="universeller Luftg\&uuml;tesensor"
DEVICE_IMG=hb-uni-sen-iaq.png
DEVICE_THUMB=hb-uni-sen-iaq_thumb.png

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"
webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="WEATHER|IAQ_LEVEL\t\${stringTableHbIaqLevel}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|IAQ_LEVEL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="WEATHER|IAQ_STATE=IAQ_GOOD\t\${stringTableHbIaqStateGood}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|IAQ_STATE=IAQ_GOOD"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="WEATHER|IAQ_STATE=IAQ_AVERAGE\t\${stringTableHbIaqStateAverage}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|IAQ_STATE=IAQ_AVERAGE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="WEATHER|IAQ_STATE=IAQ_LITTLE_BAD\t\${stringTableHbIaqStateLittleBad}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|IAQ_STATE=IAQ_LITTLE_BAD"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="WEATHER|IAQ_STATE=IAQ_BAD\t\${stringTableHbIaqStateBad}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|IAQ_STATE=IAQ_BAD"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="WEATHER|IAQ_STATE=IAQ_WORSE\t\${stringTableHbIaqStateWorse}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|IAQ_STATE=IAQ_WORSE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="WEATHER|IAQ_STATE=IAQ_VERY_BAD\t\${stringTableHbIaqStateVeryBad}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|IAQ_STATE=IAQ_VERY_BAD"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="WEATHER|BATTERY_VOLTAGE\t\${stringTableWeatherBatteryVoltage}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|BATTERY_VOLTAGE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

### Edit translate.lang.stringtable.js ###

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbIaqLevel\" : \"Luftg%FCte\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbIaqLevel\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHbIaqStateGood\" : \"Luftqualit%E4t: gut (0)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbIaqStateGood\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableHbIaqStateAverage\" : \"Luftqualit%E4t: durchschnittlich (1)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbIaqStateAverage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableHbIaqStateLittleBad\" : \"Luftqualit%E4t: unzureichend (2)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbIaqStateLittleBad\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableHbIaqStateBad\" : \"Luftqualit%E4t: schlechter (3)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbIaqStateBad\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableHbIaqStateWorse\" : \"Luftqualit%E4t: schlecht (4)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbIaqStateWorse\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableHbIaqStateVeryBad\" : \"Luftqualit%E4t: sehr schlecht (5)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbIaqStateVeryBad\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableWeatherBatteryVoltage\" : \"Batteriespannung\","
if [ -z "`cat $translate_deFile | grep \"stringTableWeatherBatteryVoltage\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi