#!/bin/sh

DEVICE="HB-IR-Rcv-RC"
DEVICE_IMG=hb-ir-rcv-rc.png
DEVICE_THUMB=hb-ir-rcv-rc_thumb.png
DEVICE_DESC="IR Receiver Remote Control"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi
