#!/bin/sh

DEVICE="HB-ES-PMSw1-USB"
DEVICE_IMG=hb-es-pmsw1-usb.png
DEVICE_THUMB=hb-es-pmsw1-usb_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-es-pmsw1-usb.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="HB_PW_METER|AVERAGING"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PW_METER|CURRENT"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PW_METER|TX_MINDELAY"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PW_METER|TX_THRESHOLD_CURRENT"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PW_METER|TX_THRESHOLD_VOLTAGE"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="HB_PW_METER|AVERAGING"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PW_METER|CURRENT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PW_METER|TX_MINDELAY"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PW_METER|TX_THRESHOLD_CURRENT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PW_METER|TX_THRESHOLD_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile


rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
