#!/bin/sh

DEVICE="HB-UNI-Sen-PF-SC"
DEVICE_IMG=hb-uni-sen-pf-sc.png
DEVICE_THUMB=hb-uni-sen-pf-sc_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-pf-sc.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A=CLOSED"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A=NO_MSG"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A=OPEN_IN"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A=OPEN_OUT"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A"
sed -i "/\($webuiSearch\)/d" $webuiFile

webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B=CLOSED"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B=NO_MSG"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B=OPEN_IN"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B=OPEN_OUT"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B"
sed -i "/\($webuiSearch\)/d" $webuiFile

webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C=CLOSED"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C=NO_MSG"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C=OPEN_IN"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C=OPEN_OUT"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|STATE=CLOSED"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|STATE=OPEN_IN"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PETFLAP_SENSOR|STATE=OPEN_OUT"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A=CLOSED"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A=NO_MSG"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A=OPEN_IN"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A=OPEN_OUT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_A"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B=CLOSED"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B=NO_MSG"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B=OPEN_IN"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B=OPEN_OUT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_B"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C=CLOSED"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C=NO_MSG"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C=OPEN_IN"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C=OPEN_OUT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|MSG_FOR_POS_C"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HB_PETFLAP_SENSOR|STATE=CLOSED"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|STATE=OPEN_IN"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PETFLAP_SENSOR|STATE=OPEN_OUT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HB_PETFLAP_SENSOR"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBPFSMsgPosA"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSMsgPosB"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSMsgPosC"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSMsgPosClosed"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSMsgPosNoMsg"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSMsgPosOpenIn"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSMsgPosOpenOut"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSStateClosed"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSStateOpenIn"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSStateOpenOut"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBPFSTitle"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.extension.js"
translate_deSearch="actionStatusControlPFSOpenIn"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="actionStatusControlPFSOpenOut"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="actionStatusControlPFSOpenClosed"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
