#!/bin/sh

DEVICE="HB-LC-Sw2-FM"
DEVICE_IMG=5_hm-lc-sw2-fm.png
DEVICE_THUMB=5_hm-lc-sw2-fm_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-lc-sw2-fm.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
