#!/bin/sh

DEVICE="HB-LC-Sw1PBU-FM"
DEVICE_IMG=PushButton-2ch-wm.png
DEVICE_THUMB=PushButton-2ch-wm_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-lc-sw1pbu-fm.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
