#!/bin/sh
# WebUI icon used from http://icons8.com 

DEVICE="HB-UNI-SenAct-8-8-RC"
DEVICE_IMG=hb-uni-senact-8-8.png
DEVICE_THUMB=hb-uni-senact-8-8_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-senact-8-8-rc.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

##########################################################################################################################

DEVICE="HB-UNI-SenAct-8-8-SC"
DEVICE_IMG=hb-uni-senact-8-8.png
DEVICE_THUMB=hb-uni-senact-8-8_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-senact-8-8-sc.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

##########################################################################################################################

DEVICE="HB-UNI-SenAct-8-8-RC-BAT"
DEVICE_IMG=hb-uni-senact-8-8-bat.png
DEVICE_THUMB=hb-uni-senact-8-8-bat_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-senact-8-8-rc-bat.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

##########################################################################################################################

DEVICE="HB-UNI-SenAct-8-8-SC-BAT"
DEVICE_IMG=hb-uni-senact-8-8-bat.png
DEVICE_THUMB=hb-uni-senact-8-8-bat_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-senact-8-8-sc-bat.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

##########################################################################################################################
