#!/bin/sh

DEVICE="HB-UNI-Sen-DIST-US"
DEVICE_IMG=hb-uni-sen-dist-us.png
DEVICE_THUMB=hb-uni-sen-dist-us_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-dist-us.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="HB_GENERIC_DIST|DISTANCE_OFFSET"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_GENERIC_DIST|SENSOR_TYPE"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="HB_GENERIC_DIST|DISTANCE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_GENERIC_DIST|DISTANCE_OFFSET"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_GENERIC_DIST|SENSOR_TYPE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_GENERIC_DIST|BATTERY_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbGenericDistDistance"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbGenericDistDistanceOffset"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbGenericDistBatteryVoltage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbGenericDistSensorType"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
