#!/bin/sh

DEVICE="HB-OU-RGB-TEALIGHT"
DEVICE_IMG=hb-ou-rgb-tealight.png
DEVICE_THUMB=hb-ou-rgb-tealight_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-ou-rgb-tealight.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB


##########################################################################################################################

DEVICE="HB-OU-RGB-TEALIGHT-BAT"
DEVICE_IMG=hb-ou-rgb-tealight-bat.png
DEVICE_THUMB=hb-ou-rgb-tealight-bat_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-ou-rgb-tealight-bat.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB