#!/bin/sh

DEVICE="HB-RC-12-EP-C"
DEVICE_IMG=hb-rc-12-ep-c.png
DEVICE_THUMB=hb-rc-12-ep-c_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-rc-ep-29c.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
