#!/bin/sh

DEVICE="HB-UNI-Sen-VOLT"
DEVICE_IMG=hb-uni-sen-volt.png
DEVICE_THUMB=hb-uni-sen-volt_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-volt.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
    sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
    sed -i "/\($DEVICE\)/d" $webuiFile
fi

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="HB_GENERIC_VOLT|HB_VOLTAGE"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi

stringtable_deSearch="HB_GENERIC_VOLT|BATTERY_VOLTAGE"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
