#!/bin/sh

DEVICE="HB-UNI-Sen-LEV-US"
DEVICE_IMG=hb-uni-sen-lev-us.png
DEVICE_THUMB=hb-uni-sen-lev-us_thumb.png
FIRMWARE_FILES=/firmware/rftypes/hb-uni-sen-lev-us*.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="CAPACITIVE_FILLING_LEVEL_SENSOR|DISTANCE_OFFSET"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="CAPACITIVE_FILLING_LEVEL_SENSOR|SENSOR_TYPE"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="ERROR=TEMP_SENSOR_FAIL"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="CAPACITIVE_FILLING_LEVEL_SENSOR|BATTERY_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="CAPACITIVE_FILLING_LEVEL_SENSOR|DISTANCE_OFFSET"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="CAPACITIVE_FILLING_LEVEL_SENSOR|SENSOR_TYPE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="CAPACITIVE_FILLING_LEVEL_SENSOR|FILLING_LITER"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="CAPACITIVE_FILLING_LEVEL_SENSOR|FILLING_HEIGHT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="ERROR=TEMP_SENSOR_FAIL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableCapacitiveFillingSensorBatteryVoltage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableCapacitiveFillingSensorDistanceOffset"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableCapacitiveFillingSensorSensorType"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableCapacitiveFillingSensorFillingLiter"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableCapacitiveFillingSensorFillingHeight"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBTempSensorFailure"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILES
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
rm -f /www/config/easymodes/HB-UNI-Sen-LEV-US_master.tcl
rm -f /www/config/easymodes/js/HBFillingLevelSensor.js
rm -f /www/config/easymodes/js/HB-UNI-Sen-LEV-US_HELP.js
