#!/bin/sh

DEVICE="HB-UNI-Sen-CAP-MOIST"
DEVICE_IMG=hb-uni-sen-cap-moist.png
DEVICE_THUMB=hb-uni-sen-cap-moist_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-cap-moist.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="CAP_MOIST_HIGH_VALUE"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="CAP_MOIST_LOW_VALUE"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="CAP_MOIST_HIGH_VALUE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="CAP_MOIST_LOW_VALUE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbCapMoistHighValue"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbCapMoistLowValue"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
