#!/bin/sh

DEVICE="HB-UNI-Sen-DUMMY-BEACON-V2"
DEVICE_IMG=hb-uni-sen-dummy-beacon.png
DEVICE_THUMB=hb-uni-sen-dummy-beacon_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-dummy-beacon-v2.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="FD_BROADCAST"


stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="FD_SIMULATE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FD_SEND_EVERY"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FD_BROADCAST"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableFdSimulate"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableFdSendEvery"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableFdBroadcast"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
