#!/bin/sh

DEVICE="HB-UNI-Sen-LDR-SC"
DEVICE_IMG=hb-uni-sen-ldr-sc.png
DEVICE_THUMB=hb-uni-sen-ldr-sc_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-ldr-sc.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

webuiSearch="HB_LDRSC|MSG_FOR_POS_A=LDROFF"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_LDRSC|MSG_FOR_POS_A=LDRON"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_LDRSC|MSG_FOR_POS_A"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_LDRSC|MSG_FOR_POS_B=LDROFF"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_LDRSC|MSG_FOR_POS_B=LDRON"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_LDRSC|MSG_FOR_POS_B"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_LDRSC|STATE=LDROFF"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_LDRSC|STATE=LDRON"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deSearch="HB_LDRSC|MSG_FOR_POS_A=LDROFF"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_LDRSC|MSG_FOR_POS_A=LDRON"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_LDRSC|MSG_FOR_POS_A"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_LDRSC|MSG_FOR_POS_B=LDROFF"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_LDRSC|MSG_FOR_POS_B=LDRON"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_LDRSC|MSG_FOR_POS_B"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_LDRSC|STATE=LDRON"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_LDRSC|STATE=LDROFF"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableMsgPosLdrOn"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableMsgPosLdrOff"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbLdrscMsgPosA"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbLdrscMsgPosB"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableStateLdrOn"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableStateLdrOff"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbLdrscThreshold"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB