#!/bin/sh

DEVICE="HB-UNI-Sen-TEMP-SC"
DEVICE_IMG=hb-uni-sen-temp-sc.png
DEVICE_THUMB=hb-uni-sen-temp-sc_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-temp-sc.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="WEATHER|ERROR=HB_ERROR_TEMPSENSOR_FAILURE"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PWRSC|STATE=PWRON"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PWRSC|STATE=PWROFF"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CONDSC|STATE=CONDABOVE"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CONDSC|STATE=CONDBELOW"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|ERROR=HB_ERROR_TEMPSENSOR_FAILURE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PWRSC|STATE=PWRON"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PWRSC|STATE=PWROFF"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CONDSC|STATE=CONDABOVE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CONDSC|STATE=CONDBELOW"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile



translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBErrorTempSensorFailure"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableStatePwrOn"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableStatePwrOff"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableStateCondAbove"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableStateCondBelow"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
