#!/bin/sh

DEVICE="HB-UNI-Sen-LEV-US"
DEVICE_IMG=hb-uni-sen-lev-us.png
DEVICE_THUMB=hb-uni-sen-lev-us_thumb.png

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
rm -f /www/config/easymodes/HB-UNI-Sen-LEV-US_master.tcl
rm -f /www/config/easymodes/js/HBFillingLevelSensor.js
rm -f /www/config/easymodes/js/HB-UNI-Sen-LEV-US_HELP.js
