#!/bin/sh

DEVICE="HB-RC-4-TOUCH"
DEVICE_IMG=hb-rc-4-touch.png
DEVICE_THUMB=hb-rc-4-touch_thumb.png

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "; sed -i "s/\($devdescrSearch\)//g" $devdescrFile

rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

rm -f $FIRMWARE_FILE
