#!/bin/sh

DEVICE="HB-RC-12-EP-C"
DEVICE_IMG=hb-rc-12-ep-c.png
DEVICE_THUMB=hb-rc-12-ep-c_thumb.png

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "; sed -i "s/\($devdescrSearch\)//g" $devdescrFile

rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

DEVICE="HB-RC-12-EP-BW"
DEVICE_IMG=hb-rc-12-ep-bw.png
DEVICE_THUMB=hb-rc-12-ep-bw_thumb.png

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "; sed -i "s/\($devdescrSearch\)//g" $devdescrFile

rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
