#!/bin/sh

DEVICE="HB-UNI-Sen-RFID-RC"
DEVICE_IMG=hb-uni-sen-rfid-rc.png
DEVICE_THUMB=hb-uni-sen-rfid-rc_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-rfid-rc.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
    sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
    sed -i "/\($DEVICE\)/d" $webuiFile
fi

cd /www
patch -R -p3 -i /usr/local/addons/jp-hb-devices-addon/patch/hb-uni-sen-rfid-rc.patch 
[[ -f ./rega/esp/datapointconfigurator.fn.orig ]] && rm ./rega/esp/datapointconfigurator.fn.orig

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
