#!/bin/sh

DEVICE="HB-UNI-Sen-TEMP-MAX6675-DT"
DEVICE_IMG=hb-uni-sen-temp-max6675-dt.png
DEVICE_THUMB=hb-uni-sen-temp-max6675-dt_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-temp-max6675-dt.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

# der Rest wird vom HB-UNI-Sen-TEMP-MAX6675 entfernt

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
