#!/bin/sh

DEVICE="HB-UNI-Sen-CURRENT"
DEVICE_IMG=hb-uni-sen-current.png
DEVICE_THUMB=hb-uni-sen-curent_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-current.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="HB_GENERIC|HB_CURRENT"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_SAMPLE_TIME"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_MEASURE_INTERVAL"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CONDITIONCHECK_AVERAGE"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CHECK_EACH_MEASURE"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CHECK_AVERAGE"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="CURRENTSENSOR_FAIL"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="HB_GENERIC|HB_CURRENT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_SAMPLE_TIME"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_MEASURE_INTERVAL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CONDITIONCHECK_AVERAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CHECK_EACH_MEASURE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CHECK_AVERAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="CURRENTSENSOR_FAIL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHBCurrent"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBSampleTime"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBMeasureInterval"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBConditionCheckAverage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBCheckEachMeasure"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBCheckAverage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBCurrentSensorFailure"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
