#!/bin/sh

DEVICE="HB-UNI-Sen-PC-WM"
DEVICE_IMG=hb-uni-sen-pc-wm.png
DEVICE_THUMB=hb-uni-sen-pc-wm_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-pc-wm.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="HB_METER_READING"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_METER_CONSTANT_WATER"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_ANALOG_LOW_THRESHOLD"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_TAHB_ANALOG_HIGH_THRESHOLDRA"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_PULSE_DELAY_MS"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_COUNT_INITIAL_VALUE"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="HB_METER_READING"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_METER_CONSTANT_WATER"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_ANALOG_LOW_THRESHOLD"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_ANALOG_HIGH_THRESHOLD"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_PULSE_DELAY_MS"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_COUNT_INITIAL_VALUE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="OAPC_ERROR"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FRAM_ERROR"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbMeterReading"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbAnalogLowThreshold"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbAnalogHighThreshold"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbPulseDelayMS"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbCountInitialValue"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbMeterConstantWater"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbOapcError"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbFramError"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
