#!/bin/sh

DEVICE="HB-UNI-Sen-IAQ"
DEVICE_IMG=hb-uni-sen-iaq.png
DEVICE_THUMB=hb-uni-sen-iaq_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-iaq.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_LEVEL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_GOOD"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_AVERAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_LITTLE_BAD"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_BAD"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_WORSE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_VERY_BAD"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="WEATHER|BATTERY_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbIaqLevel"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqStateGood"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqStateAverage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqStateLittleBad"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqStateBad"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqStateWorse"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqStateVeryBad"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableWeatherBatteryVoltage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
