#!/bin/sh

DEVICE="HB-UNI-Sen-DUMMY-BEACON"
DEVICE_IMG=hb-uni-sen-dummy-beacon.png
DEVICE_THUMB=hb-uni-sen-dummy-beacon_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-dummy-beacon.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="FD_ENABLED"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="FD_ENABLED=TRUE"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="FD_ENABLED=FALSE"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="FD_DEVICE_ID"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="FD_CYCLIC_TIMEOUT"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="FD_STATUS"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="FD_ENABLED"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FD_ENABLED=TRUE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FD_ENABLED=FALSE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FD_DEVICE_ID"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FD_CYCLIC_TIMEOUT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FD_STATUS"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableFdEnabled"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableFdEnabledTrue"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableFdEnabledFalse"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableFdDeviceId"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableFdCyclicTimeout"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableFdStatus"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
