#!/bin/sh

DEVICE="HB-OU-MOT-FAN"
DEVICE_IMG=hb-ou-mot-fan.png
DEVICE_THUMB=hb-ou-mot-fan_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-ou-mot-fan.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="FAN|LEVEL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FAN|OLD_LEVEL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="FAN|RAMP_TIME"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbFanLevel"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbFanOldLevel"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbFanRampTime"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

channelsFile="/www/rega/esp/channels.htm"
channelsSearch="servoOldVal"
sed -i "/\(${channelsSearch}\)/d" $channelsFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
