#!/bin/sh

DEVICE="HB-RC-4-Dis-TH"
DEVICE_IMG=hb-rc-4-dis-th.png
DEVICE_THUMB=hb-rc-4-dis-th_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-rc-4-dis-th.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "; sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"; sed -i "/\($DEVICE\)/d" $webuiFile

webuiSearch="HB_DEFAULT_DISPLAY_MODE"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_TEMP_AND_HUMIDITY"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_TEMP_ONLY"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_DISPLAY_TIMEOUT"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_EP_SHOW_HEADER"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_HEADERLINE"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HBTEXTLINE_UPPER"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HBTEXTLINE_LOWER"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_HUMIDITY_OFFSET"; sed -i "/\($webuiSearch\)/d" $webuiFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbDisplayTimeout"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbTempAndHumidity"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbTempOnly"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbDefaultDisplayMode"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbTextLineUpper"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbTextLineLower"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbEpShowHeader"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbHeaderLine"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbHumidityOffset"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile


rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
