#!/bin/sh

DEVICE="HB-UNI-Sen-PH"
DEVICE_IMG=hb-uni-sen-ph.png
DEVICE_THUMB=hb-uni-sen-ph_thumb.png

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
