#!/bin/sh

DEVICE="HB-OU-MP3-LED"
DEVICE_IMG=hb-ou-mp3-led.png
DEVICE_THUMB=hb-ou-mp3-led_thumb.png

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

rm -f /www/config/easymodes/signal_hbchime_ch_link.tcl
rm -f /www/config/easymodes/signal_hbled_ch_link.tcl
rm -f /www/rega/pages/msg/setHBOUCFMMode.htm
rm -rf /www/config/easymodes/SIGNAL_CHIMEHB
rm -rf /www/config/easymodes/SIGNAL_LEDHB

rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
