#!/bin/sh

DEVICE="HB-RC-12-EP-C"
DEVICE_IMG=hb-rc-12-ep-c.png
DEVICE_THUMB=hb-rc-12-ep-c_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-rc-ep-29c.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="HB_EP_TEXT_COLORED"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_EP_ICON_COLORED"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_EP_ALIGN_CENTER_NO_ICON"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="HB_EP_TEXT_COLORED"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_EP_ICON_COLORED"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_EP_ALIGN_CENTER_NO_ICON"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbEpTextColored"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbEpIconColored"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbEpAlignCenterNoIcon"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
