#!/bin/sh

DEVICE="HB-DIS-EP-42BW"
DEVICE_IMG=hb-dis-ep-42bw.png
DEVICE_THUMB=hb-dis-ep-42bw_thumb.png
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

DEVICE="HB-DIS-EP-42BW-MAINS"
DEVICE_IMG=hb-dis-ep-42bw-mains.png
DEVICE_THUMB=hb-dis-ep-42bw-mains_thumb.png
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

DEVICE="HB-DIS-EP-75BW"
DEVICE_IMG=hb-dis-ep-75bw.png
DEVICE_THUMB=hb-dis-ep-75bw_thumb.png
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile


DEVICE="HB-DIS-EP-75BW-MAINS"
DEVICE_IMG=hb-dis-ep-75bw-mains.png
DEVICE_THUMB=hb-dis-ep-75bw-mains_thumb.png
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

indexFile="/www/rega/pages/index.htm"
indexFileSearch="jp_webui_inc.js"
sed -i "/${indexFileSearch}/d" $indexFile

rm -rf /www/ise/img/icons_hb_dis_ep_75bw
rm -f /www/config/easymodes/HB-DIS-EP-42BW_dev_master.tcl
rm -f /www/config/easymodes/HB-DIS-EP-75BW_dev_master.tcl
rm -f /www/config/easymodes/MASTER_LANG/HB-DIS-EP-42BW_HELP.js
rm -f /www/config/easymodes/MASTER_LANG/HB-DIS-EP-75BW_HELP.js
