#!/bin/sh

DEVICE="HB-UNI-Sen-IAQ"
DEVICE_IMG=hb-uni-sen-iaq.png
DEVICE_THUMB=hb-uni-sen-iaq_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-iaq.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
    sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
    sed -i "/\($DEVICE\)/d" $webuiFile
fi

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_LEVEL"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_GOOD"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_AVERAGE"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_LITTLE_BAD"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_BAD"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_WORSE"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi
stringtable_deSearch="WEATHER|IAQ_STATE=IAQ_VERY_BAD"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi
stringtable_deSearch="WEATHER|BATTERY_VOLTAGE"
if [ "`cat $stringtable_deFile | grep \"$stringtable_deSearch\"`" ]; then
	sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
fi

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbIaqLevel"
if [ "`cat $translate_deFile | grep \"$translate_deSearch\"`" ]; then
	sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
fi
translate_deSearch="stringTableHbIaqStateGood"
if [ "`cat $translate_deFile | grep \"$translate_deSearch\"`" ]; then
	sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
fi
translate_deSearch="stringTableHbIaqStateAverage"
if [ "`cat $translate_deFile | grep \"$translate_deSearch\"`" ]; then
	sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
fi
translate_deSearch="stringTableHbIaqStateLittleBad"
if [ "`cat $translate_deFile | grep \"$translate_deSearch\"`" ]; then
	sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
fi
translate_deSearch="stringTableHbIaqStateBad"
if [ "`cat $translate_deFile | grep \"$translate_deSearch\"`" ]; then
	sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
fi
translate_deSearch="stringTableHbIaqStateWorse"
if [ "`cat $translate_deFile | grep \"$translate_deSearch\"`" ]; then
	sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
fi
translate_deSearch="stringTableHbIaqStateVeryBad"
if [ "`cat $translate_deFile | grep \"$translate_deSearch\"`" ]; then
	sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
fi
translate_deSearch="stringTableWeatherBatteryVoltage"
if [ "`cat $translate_deFile | grep \"$translate_deSearch\"`" ]; then
	sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
fi

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
