#!/bin/sh

DEVICE="HB-LC-Bl2-RD"
DEVICE_IMG=hb-lc-bl2-rd.png
DEVICE_THUMB=hb-lc-bl2-rd_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-lc-bl2-rd.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
