#!/bin/sh

DEVICE="HB-OU-AF-SEN-TEMP"
DEVICE_IMG=hb-ou-af-sen-temp.png
DEVICE_THUMB=hb-ou-af-sen-temp_thumb.png

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

channelsFile="/www/rega/esp/channels.htm"
channelsSearch="airflapOldVal"
sed -i "/\(${channelsSearch}\)/d" $channelsFile

rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
