#!/bin/sh

DEVICE="HB-RC-4-Dis-TH"
DEVICE_IMG=hb-rc-4-dis-th.png
DEVICE_THUMB=hb-rc-4-dis-th_thumb.png
FIRMWARE_FILES=/firmware/rftypes/hb-rc-4-dis-th*.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "; sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"; sed -i "/\($DEVICE\)/d" $webuiFile

webuiSearch="HB_DEFAULT_DISPLAY_MODE"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_DISPLAY_HALF_DEGREE"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_TEMP_AND_HUMIDITY"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_TEMP_ONLY"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_DISPLAY_TIMEOUT"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_EP_SHOW_HEADER"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_HEADERLINE"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HBTEXTLINE_UPPER"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HBTEXTLINE_LOWER"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_HUMIDITY_OFFSET"; sed -i "/\($webuiSearch\)/d" $webuiFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbDisplayTimeout"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbDisplayHalfDegree"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbTempAndHumidity"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbTempOnly"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbDefaultDisplayMode"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbTextLineUpper"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbTextLineLower"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbEpShowHeader"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbHeaderLine"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbHumidityOffset"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

####  HB-RC-4-Dis-TH-CRG

DEVICE="HB-RC-4-Dis-TH-CRG"
DEVICE_IMG=hb-rc-4-dis-th-crg.png
DEVICE_THUMB=hb-rc-4-dis-th-crg_thumb.png

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "; sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"; sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="HB_CRGSC|MSG_FOR_POS_A=CRGOFF"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CRGSC|MSG_FOR_POS_A=CRGON"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CRGSC|MSG_FOR_POS_A"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CRGSC|MSG_FOR_POS_B=CRGOFF"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CRGSC|MSG_FOR_POS_B=CRGON"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CRGSC|MSG_FOR_POS_B"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CRGSC|STATE=CRGOFF"; sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_CRGSC|STATE=CRGON"; sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="HB_CRGSC|MSG_FOR_POS_A=CRGOFF"; sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CRGSC|MSG_FOR_POS_A=CRGON"; sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CRGSC|MSG_FOR_POS_A"; sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CRGSC|MSG_FOR_POS_B=CRGOFF"; sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CRGSC|MSG_FOR_POS_B=CRGON"; sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CRGSC|MSG_FOR_POS_B"; sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CRGSC|STATE=CRGON"; sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_CRGSC|STATE=CRGOFF"; sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableMsgPosCrgOn"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableMsgPosCrgOff"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbCrgscMsgPosA"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbCrgscMsgPosB"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableStateCrgOn"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableStateCrgOff"; sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

rm -f $FIRMWARE_FILES
