#!/bin/sh
# WebUI icon used from http://icons8.com 

ADDON_NAME=`basename "$0"`

ADDON_DIR=/usr/local/addons/${ADDON_NAME}
WWW_DIR=/etc/config/addons/www/${ADDON_NAME}
LOGFILE=/var/log/$ADDON_NAME.log
ERRFILE=/var/log/$ADDON_NAME.err
FIRMWARE_DIR=/firmware/rftypes
CUSTOMIZED_FIRMWARE_DIR=${ADDON_DIR}/customized_firmware
RC_DIR=/usr/local/etc/config/rc.d
CK_FIRMWARE_FILE=${FIRMWARE_DIR}/hb-uni-sen-cap-moist.xml

PATCHVERSION=0
check_ccu_fw_version()
{
 model=`cat /boot/VERSION   | awk -F'[=.]' {'print $2'}`
 version=`cat /boot/VERSION | awk -F'[=.]' {'print $3'}`
 build=`cat /boot/VERSION   | awk -F'[=.]' {'print $4'}`

 if [ $model -ge 3 ] && [ $version -ge 45 ]; then
  PATCHVERSION=2
 else
  PATCHVERSION=1
 fi
 
 echo "Found $model.$version.$build - using patchversion $PATCHVERSION"
}

MONIT=0
check_monit()
{
  MONIT=`ps -ef|grep \/usr\/bin\/monit|grep -v grep|wc -l`
}

case "$1" in
    ""|start)
      if [ ! -f ${ADDON_DIR}/installed ] || [ ! -f ${CK_FIRMWARE_FILE} ]; then       
      
        #### Check if monit process exists
        check_monit
        
        if [ $MONIT -ge 1 ]; then
          echo "Stopping monitoring service for ReGaHss and RFD"
          /usr/bin/monit unmonitor ReGaHss
          /usr/bin/monit unmonitor rfd
        fi
      
        /etc/init.d/S70ReGaHss stop
        /etc/init.d/S61rfd stop
		    
        mount -o remount,rw /
	    	
        cd ${ADDON_DIR}
        cp -ar www/* /www/
        chown root:root /www/config/img/devices/250/hb-*
        chmod 755 /www/config/img/devices/250/hb-*
        chown root:root /www/config/img/devices/50/hb-*
        chmod 755 /www/config/img/devices/50/hb-*
        chown root:root /www/ise/img/icons_hm_dis_ep_wm55/24/*
        chmod 755 /www/ise/img/icons_hm_dis_ep_wm55/24/*
        
        ### Patch some files ###
        check_ccu_fw_version

        cd /www

        echo "######## REVOKE OLD APPLIED PATCHES ########"
        patch -R -p3 -i ${ADDON_DIR}/patch/revoke/jp.patch 
        patch -R -p3 -i ${ADDON_DIR}/patch/revoke/hb-dis-ep-42bw.patch
        patch -R -p3 -i ${ADDON_DIR}/patch/revoke/hb-ou-mp3-led_side.inc.not_used.patch
        patch -R -p3 -i ${ADDON_DIR}/patch/revoke/hb-uni-sen-rfid-rc.patch
        patch -R -p3 -i ${ADDON_DIR}/patch/revoke/programs_wrong_encodeStringStatusDisplay.patch
        
        echo "######## APPLY COMMON PATCHES ########"
        patchsubdir=common
        for patchfile in ${ADDON_DIR}/patch/$patchsubdir/* ; do
          patch -N -p3 -i $patchfile
        done
        
        echo "######## APPLY VERSION DEPENDEND PATCHES ########"
        if [ $PATCHVERSION -le 1 ]; then
          patchsubdir=le_343
        else
          patchsubdir=ge_345
        fi
      
        for patchfile in ${ADDON_DIR}/patch/$patchsubdir/* ; do
          patch -N -p3 -i $patchfile
        done
         
        [[ -f ./config/ic_common.tcl.orig ]] && rm ./config/ic_common.tcl.orig
        [[ -f ./rega/esp/side.inc.orig ]] && rm ./rega/esp/side.inc.orig
        [[ -f ./rega/esp/functions.fn.orig ]] && rm ./rega/esp/functions.fn.orig
        [[ -f ./rega/pages/tabs/admin/views/programs.htm.orig ]] && rm ./rega/pages/tabs/admin/views/programs.htm.orig
        [[ -f ./rega/esp/datapointconfigurator.fn.orig ]] && rm ./rega/esp/datapointconfigurator.fn.orig
        [[ -f ./webui/webui.js.orig ]] && rm ./webui/webui.js.orig

        ### Create Symlink to include own js file
        ln -s /usr/local/addons/jp-hb-devices-addon/js/jp_webui_inc.js /www/webui/js/extern/jp_webui_inc.js
	    	    
        cd ${ADDON_DIR}
        echo "Running scripts..."    
        for f in ${ADDON_DIR}/install_* ; do echo "  - $(basename $f)"; ./$(basename $f) > $LOGFILE 2>$ERRFILE; done

	    echo "Copying customized firmware files..."
        cp ${CUSTOMIZED_FIRMWARE_DIR}/* ${ADDON_DIR}${FIRMWARE_DIR}/

        echo "Creating symlinks for firmware files..."
        for f in ${ADDON_DIR}${FIRMWARE_DIR}/* ; do rm -f ${FIRMWARE_DIR}/$(basename $f); ln -s $f ${FIRMWARE_DIR}/$(basename $f); echo "  - $(basename $f)"; done

        sync
        mount -o remount,ro /
        touch ${ADDON_DIR}/installed
		    
        /etc/init.d/S61rfd start
        /etc/init.d/S70ReGaHss start
        
        if [ $MONIT -ge 1 ]; then
          echo "Starting monitoring service for ReGaHss and RFD"
          /usr/bin/monit monitor ReGaHss
          /usr/bin/monit monitor rfd
        fi
      else
        echo "Checking for subsequent customized firmware files..."
        changed=0
	
        for f in ${ADDON_DIR}${FIRMWARE_DIR}/* ; do
	      $(cmp -s ${CUSTOMIZED_FIRMWARE_DIR}/$(basename $f) $f)
          rc=$?
          if [ $rc -eq 1 ]; then
            echo "Difference detected for $(basename $f). Copying..."
            cp ${CUSTOMIZED_FIRMWARE_DIR}/$(basename $f) $f
            let changed++
          fi
        done

        if [ $changed -gt 0 ]; then
          echo "$changed Firmware file(s) changed - restarting RFD"
          /etc/init.d/S61rfd restart
        else
          echo "Nothing changed - nothing to do"
        fi

      fi
    ;;

    stop)
      echo "Nothing to stop..."
    ;;

    uninstall)
      mount -o remount,rw /
		
      cd ${ADDON_DIR}
      echo "Running scripts..."    
      for f in ${ADDON_DIR}/uninstall_* ; do echo "  - $(basename $f)"; ./$(basename $f) > $LOGFILE 2>$ERRFILE; done
      
      check_ccu_fw_version

      cd /www
      
      echo "######## REVOKE COMMON PATCHES ########"
      patchsubdir=common
      for patchfile in ${ADDON_DIR}/patch/$patchsubdir/* ; do
        patch -R -p3 -i $patchfile
      done
      
      echo "######## REVOKE VERSION DEPENDEND PATCHES ########"
      if [ $PATCHVERSION -le 1 ]; then
        patchsubdir=le_343
      else
        patchsubdir=ge_345
      fi
     
      for patchfile in ${ADDON_DIR}/patch/$patchsubdir/* ; do
        patch -R -p3 -i $patchfile
      done

      [[ -f ./webui/webui.js.orig ]] && rm ./webui/webui.js.orig
      [[ -f ./rega/esp/datapointconfigurator.fn.orig ]] && rm ./rega/esp/datapointconfigurator.fn.orig
      [[ -f ./rega/esp/functions.fn.orig ]] && rm ./rega/esp/functions.fn.orig
      [[ -f ./rega/esp/side.inc.orig ]] && rm ./rega/esp/side.inc.orig
      [[ -f ./rega/pages/tabs/admin/views/programs.htm.orig ]] && rm ./rega/pages/tabs/admin/views/programs.htm.orig
      [[ -f ./config/ic_common.tcl.orig ]] && rm ./config/ic_common.tcl.orig
      [[ -f ./webui/js/extern/jp_webui_inc.js ]] && rm ./webui/js/extern/jp_webui_inc.js
  		    		    		
      cd /
      rm -rf $ADDON_DIR
      rm -rf $WWW_DIR
      rm -f ${RC_DIR}/${ADDON_NAME}
      sync
      mount -o remount,ro /
    ;;
  
    restart|reload)
      # Operations to stop and start (restart) the addon
    ;;

    info)
      echo "Info: <center><b>JP HB Devices Support Addon</b></center><br />" 
      echo "Info: <center><img src='../addons/${ADDON_NAME}/${ADDON_NAME}.png'></img></center><br/><a href='https://github.com/jp112sdl/${ADDON_NAME}'>https://github.com/jp112sdl/${ADDON_NAME}</a>" 
      echo "Version: $(cat ${ADDON_DIR}/VERSION)"                                                                                                                                                                                       
      echo "Name: JP HB Devices"                                                                                                                                                                                                        
      echo "Operations: uninstall"                                                                                                                                                                                                      
      #echo "Config-Url: ${CONFIG_URL}"                                                                                                                                                                                                 
      echo "Update: /addons/${ADDON_NAME}/update-check.cgi"
    ;;
	
    *)
      echo "Usage: $ADDON_NAME {start|stop|restart|info|uninstall}" >&2
      exit 1
    ;;

esac

exit $?
