#!/bin/sh
# WebUI icon used from http://icons8.com 
target="UNDEFINED"
if [ "$1" != "" ]; then
  target=$1
fi
echo $target

if [ "$1" = "CCU2" ]; then
  mount -t ubifs ubi1:user /usr/local
elif [ "$1" = "HM-RASPBERRYMATIC" ] || [ "$1" = "CCU3" ]; then
  mount /usr/local
fi  

ADDON_NAME=jp-hb-devices-addon
RC_DIR=/usr/local/etc/config/rc.d
ADDON_DIR=/usr/local/addons/$ADDON_NAME

# Deinstallieren einer bestehenden Addon-Installation
if [ -f ${RC_DIR}/${ADDON_NAME} ]; then
  ${RC_DIR}/${ADDON_NAME} uninstall
fi

# Startscript anlegen
cp -af rc.d/$ADDON_NAME ${RC_DIR}/
chmod +x ${RC_DIR}/$ADDON_NAME

# Addon-Verzeichnis anlegen
mkdir -p ${ADDON_DIR}
cp -af addon/* ${ADDON_DIR}
chmod 755 ${ADDON_DIR}

sync

if [ "$1" = "HM-RASPBERRYMATIC" ] || [ "$1" = "CCU3" ]; then
  exit 10
fi
