#!/bin/sh
# WebUI icon used from http://icons8.com 

RL_FILE=/lib/udev/rules.d/99-hmip-rfusb.rules
CK_FILE=/www/api/methods/ccu/downloadFirmware.tcl
if [ -e "$CK_FILE" ] && grep -iq 'to\|bu' "$CK_FILE" ; then exit 13; fi
if [ -e "$RL_FILE" ] && grep -iq 'hmul'   "$RL_FILE" ; then exit 13; fi

target="UNDEFINED"
if [ "$1" != "" ]; then
  target=$1
fi
echo "TARGET="$target

if [ "$1" = "CCU2" ]; then
  mount -t ubifs ubi1:user /usr/local
elif [ "$1" = "HM-RASPBERRYMATIC" ] || [ "$1" = "CCU3" ]; then
  mount /usr/local
elif [ "$1" = "" ]; then
  echo "NOTHING TO MOUNT"
else
  exit 14
fi

ADDON_NAME=jp-hb-devices-addon
RC_DIR=/usr/local/etc/config/rc.d
ADDON_DIR=/usr/local/addons/${ADDON_NAME}-new

# Startscript anlegen
cp -af rc.d/$ADDON_NAME ${RC_DIR}/
chmod +x ${RC_DIR}/$ADDON_NAME

# Addon-Verzeichnis anlegen
mkdir -p ${ADDON_DIR}
cp -af addon/* ${ADDON_DIR}
chmod 755 ${ADDON_DIR}

sync

if [ "$1" = "HM-RASPBERRYMATIC" ] || [ "$1" = "CCU3" ]; then
  exit 10
fi
